baseURL = 'https://ratulotron.github.io/'
languageCode = 'en-us'
title = 'Ratul Minhaz'
theme = 'bold'

[params]
  description = "Data Engineer based in Berlin"
  author = "Ratul Minhaz"
  site_title = "Ratul Minhaz"
  home_subtitle = "Data Engineer based in Berlin"
  blog_subtitle = "Thoughts & Ideas"
  post_subtitle = "Blog Post"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
